### ISSUE TITLE
[mac][mariadb] Installation error

### ISSUE THREAD

**Issue by sebastianblum** [prooph/proophessor-do#144]
I'm playing with the manual installation and I got these error running `php scripts/create_event_stream.php`

```
php scripts/create_event_stream.php
PHP Fatal error:  Uncaught Prooph\EventStore\Pdo\Exception\RuntimeException: Error during createSchemaFor: 42000; 1064; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL,
    `aggregate_id` CHAR(36) CHARACTER SET utf8 COLLATE utf8_bin GENERA' at line 8 in /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/pdo-event-store/src/MySqlEventStore.php:805
Stack trace:
#0 /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/pdo-event-store/src/MySqlEventStore.php(180): Prooph\EventStore\Pdo\MySqlEventStore->createSchemaFor('_4228e4a00331b5...')
#1 /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/event-store/src/ActionEventEmitterEventStore.php(74): Prooph\EventStore\Pdo\MySqlEventStore->create(Object(Prooph\EventStore\Stream))
#2 /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/common/src/Event/ProophActionEventEmitter.php(57): Prooph\EventStore\ActionEventEmitterEventStore-> in /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/pdo-event-store/src/MySqlEventStore.php on line 805

Fatal error: Uncaught Prooph\EventStore\Pdo\Exception\RuntimeException: Error during createSchemaFor: 42000; 1064; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL,
    `aggregate_id` CHAR(36) CHARACTER SET utf8 COLLATE utf8_bin GENERA' at line 8 in /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/pdo-event-store/src/MySqlEventStore.php:805
Stack trace:
#0 /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/pdo-event-store/src/MySqlEventStore.php(180): Prooph\EventStore\Pdo\MySqlEventStore->createSchemaFor('_4228e4a00331b5...')
#1 /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/event-store/src/ActionEventEmitterEventStore.php(74): Prooph\EventStore\Pdo\MySqlEventStore->create(Object(Prooph\EventStore\Stream))
#2 /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/common/src/Event/ProophActionEventEmitter.php(57): Prooph\EventStore\ActionEventEmitterEventStore-> in /Users/sebastianblum/PhpstormProjects/proophessor-do/vendor/prooph/pdo-event-store/src/MySqlEventStore.php on line 805
```

My system is
* Mac Book Pro
* MariaDB: 10.2.9-MariaDB Homebrew

any ideas to fix that problem?

**Comment by sebastianblum** [comment]
I found now the mariadb folder and will create a pull request
